### ISSUE TITLE
Agate does not send TLS shutdown

### ISSUE THREAD

**Issue by balazsbotond** [mbrubeck/agate#100]
There's an ongoing discussion on the mailing list that most servers fail to send an (otherwise mandatory) TLS shutdown. Agate is among them:

```
$ agunua gemini://botond.online/doesnotexist
Warning, no TLS shutdown received from the server
Problem, Not found (extra message: "Not found, sorry.").
```

(The [agunua tool](https://framagit.org/bortzmeyer/agunua) is probably the easiest way to check this.)

**Comment by Johann150** [comment]
This only seems to occur for error messages, successful requests seemed to work correctly before. For error messages it should be fixed by 99494e148be72a84ebecb3c4a322c8234d05f660.

Please note that there seems to be an issue with Agunua too. I checked using `openssl s_client -connect 127.0.0.1:1965 -servername localhost -msg` and it shows that both sides sent `close_notify`:

```
$ openssl s_client -connect 127.0.0.1:1965 -servername localhost -msg 
[...]
---
SSL handshake has read 2109 bytes and written 381 bytes
Verification error: self signed certificate
---
[...]
gemini://localhost/doesnotexist^M
>>> ??? [length 0005]
    17 03 03 00 32
>>> TLS 1.3 [length 0001]
    17
<<< ??? [length 0005]
    17 03 03 00 27
51 Not found, sorry.
<<< ??? [length 0005]
    17 03 03 00 13
<<< TLS 1.3 [length 0001]
    15
<<< TLS 1.3, Alert [length 0002], warning close_notify
    01 00
closed
>>> ??? [length 0005]
    17 03 03 00 13
>>> TLS 1.3 [length 0001]
    15
>>> TLS 1.3, Alert [length 0002], warning close_notify
    01 00
```

But when I then checked the same URL with agunua, it showed the unchanged error message:
```
./agunua gemini://localhost/doesnotexist
Warning, no TLS shutdown received from the server
Problem, Not found (extra message: "Not found, sorry.").
```
