### ISSUE TITLE
agate 3.2.3 debian  - Meta	"dovecot" 

### ISSUE THREAD

**Issue by Bschalck** [mbrubeck/agate#165]
Hy, 

I have a LXC server for Gemini.
It works fine, but sice Mid MArch ( I don't know wehn exactly ) , it seems KO.

The gemini address is gemini://txt-vostfr.devloprog.org

The result is a popup : "dovecot" ... 

Do you know why ? 

Regards

**Comment by Bschalck** [comment]
Hello,

thanks for your answer. Do you wich command can be done to test gemini url , like curl for http ? 

REgards,

**Comment by pitichampi** [comment]
Did you install some email manager or maybe some groupware ? It seems that dovecot, an IMAP web utility answers instead of gemini. Can you test by running (in terminal on your server) this command :

`sudo lsof -i:1965`

You should see your gemini server. If you see something about dovecot or something else it means that this server is using your 1965 port. When I run a scan on your server I see Tivoli-npm answering to the port 1965.

```
Starting Nmap 7.91 ( https://nmap.org ) at 2022-03-28 17:30 CEST
Nmap scan report for 82-65-0-139.subs.proxad.net (82.65.0.139)
Host is up (0.028s latency).

PORT     STATE SERVICE
1965/tcp open  tivoli-npm
```

Bonne journée :p

**Comment by Bschalck** [comment]
Hello pitichampi,

in fact , this gemini is behind a reversy prox, and on promox LXC.

That works since 6 months. Ans I saw since mid march that it doesn't work anymore.
ion fact , on this LXC , theris only my gemini server : 
```
[502] - 192.168.5.10 - root@web-gemini [~]$ lsof -i:1965
COMMAND  PID  USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
agate   6729 agate    6u  IPv4 815375634      0t0  TCP *:1965 (LISTEN)
[502] - 192.168.5.10 - root@web-gemini [~]$ 

```
and my firewall seems OK ... but there is no service running on this port on other LXC ... and no tivoli at all :D

**Comment by Johann150** [comment]
Tivoli is just an old assignment that used the same port before. I don't think nmap checked the service. As I said I don't know about LXC but you probably have to foward the port from the container at some point. Please check if that configuration is still as it should be because the output I got when testing is definitely not from agate.

**Comment by pitichampi** [comment]
Agate is obviously running...

And... have you tried to use a gemini client locally on your container and to connect to localhost ? Just try to figure out where is the problem... If it works locally then it's an issue somewhere with the routing...

Are you accessing your container through the proxmox monitor or through a distant ssh ?

I remember once having trouble to access a container because another took the ip (because of a wrong configuration). After restarting the whole server, I saw that another container took the connexion (you can see it in proxmox as the container remains offline). I know that's a dumb answer but... did you try restarting the proxmox server (or at least the container) ? Sorry for this dumb question but I try everything that I know...

**Comment by Bschalck** [comment]
Yep , I try to find a command-line browser for gemini, but didn't find one :/

**Comment by Johann150** [comment]
You could try using https://tildegit.org/acdw/bollux

**Comment by pitichampi** [comment]
You can give a chance to https://github.com/makeworld-the-better-one/amfora or https://bombadillo.colorfield.space (just found them on gemini://geminiquickst.art/)

**Comment by Bschalck** [comment]
I think that the problem the SSL . 
I try to connect with Borax : 

```
[502] - 192.168.5.10 - root@web-gemini [~]$ ./bollux localhost:1965
139761022448960:error:14094419:SSL routines:ssl3_read_bytes:tlsv1 alert access denied:../ssl/record/rec_layer_s3.c:1543:SSL alert number 49
bollux:die             : Empty response code.

```

**Comment by Johann150** [comment]
SSL/TLS is not the issue. That error is caused because you used `localhost` as the hostname which does not work because the certificate is not issued for the `localhost` hostname.

As I said multiple times before, I'm pretty sure the issues that are visible on the outside are not caused by agate or the container it runs in. Please check how port 1965 is forwarded or used on the *host system*.

**Comment by Bschalck** [comment]
Well ,as you said , the problem is not du to the certs. ... But my fu**ing firewall .

The problem is resolved.
Sorry and thanks for your attentions and answers.
