### ISSUE TITLE
PEM certificate support?

### ISSUE THREAD

**Issue by kallisti5** [mbrubeck/agate#171]
Kubernetes holds PEM certificates, and providers like letsencrypt deal in PEM certificates.  Any chance of adding support for PEM as a "backup choice" to DER?

I actually can't think of the last application i've seen that used DER.

**Comment by kallisti5** [comment]
Hm.  I tried having our container convert our Lets Encrypt PEM certificates to DER.  Isn't going well :laughing:
```
$ openssl s_client -connect lofi.haiku-os.org:1965
CONNECTED(00000003)
depth=0 CN = lofi.haiku-os.org
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = lofi.haiku-os.org
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN = lofi.haiku-os.org
verify return:1
---
Certificate chain
 0 s:CN = lofi.haiku-os.org
   i:C = US, O = Let's Encrypt, CN = R3
---
Server certificate
-----BEGIN CERTIFICATE-----
.
.
-----END CERTIFICATE-----
subject=CN = lofi.haiku-os.org

issuer=C = US, O = Let's Encrypt, CN = R3

---

```

Lagrange isn't trusting it even though the certificates are fully CA validated to Lets Encrypt.

My conversion process is here:
https://github.com/haiku/website-gemini/blob/master/start.sh#L13

**Comment by Johann150** [comment]
Agate switched from PEM to DER in version 3.0.0 because that is what the used library uses without adding additional dependencies and compile time. There is a documented migration procedure in the changelog that worked for me at the time: https://github.com/mbrubeck/agate/blob/master/CHANGELOG.md#300---2021-03-27 It seems similar to what you are doing so I'm not sure what the difference is and also do not have the resources to look into that right now.

Gemini does not (have to) use certificates issued by CAs because of the TOFU scheme, so I'm not sure why you want to use a Let's Encrypt certificate with Agate. The intended path is to let Agate generate the certificate so I do not think PEM support should be necessary.

**Comment by kallisti5** [comment]
Most gemini sites seem to provide CA validated certificates.  I haven't actually stumbled across any not using local CA verified.

With that said.. generally you can provide a full chain of trust within PEM encoded certifcates by appending them to a single .crt / pem file.    I don't think you can store multiple certificates in a DER.. which means that change removed the ability to provide full chain of trust when required.

**Comment by Johann150** [comment]
> Clients can validate TLS connections however they like (including not at all) but the **strongly RECOMMENDED** approach is to implement a lightweight "TOFU" certificate-pinning system which treats **self-signed certificates** as first- class citizens. This greatly reduces TLS overhead on the network (**only one cert needs to be sent, not a whole chain**) and lowers the barrier to entry for setting up a Gemini site (no need to pay a CA or setup a Let's Encrypt cron job, just make a cert and go).

&mdash; Gemini specification at gemini://gemini.circumlunar.space/docs/specification.gmi - § 4.2 - emphasis mine

From my understanding of the above, a full chain of trust is *never* required for the recommended implementation of the Gemini protocol. In other words, it is not a bug, it is a feature.
