### ISSUE TITLE
Agate conflicting with either Nginx or Nextcloud

### ISSUE THREAD

**Issue by catspacer** [mbrubeck/agate#32]
When running Agate as a systemd-service I can not login to my Nextcloud (setup with Nginx). Stopping the agate-service solves the problem.

Agate doesn't need port 443 or 80 as far as I understand?

**Comment by sherpashrapnel** [comment]
I'm running it on Debian 10 and installed agate through cargo. Certificates generated according to your example, but I move them to /root. Made a new user called gemini and in their home folder I make a file called start-agate.sh that looks like this:

#!/usr/bin/env bash

sudo /home/gemini/.cargo/bin/agate --content /home/gemini/content/ \
      --key /root/key.rsa \
      --cert /root/cert.pem \
      --addr [::]:1965 \
      --addr 0.0.0.0:1965 \
      --hostname my-gemini-site-url.xyz \
      --lang en-US &

Then I create the file /etc/systemd/system/agate.service that looks like this:
[Service]
Type=simple
RemainAfterExit=yes
ExecStart=/home/gemini/start-agate.sh
TimeoutStartSec=0

[Install]
WantedBy=default.target

**Comment by Johann150** [comment]
So it is pretty much the default. Nothing that would suggest an error source for me. Only idea I would have is the old "turn it off and on again" trick.

On another note, this setup is not ideal since you cannot monitor Agate's logs this way. Also I think by using `sudo` you are effectively running Agate as root, making the gemini user superfluous. You can take a look at the `tools/debian/gemini.service` file for an example service file. I don't think this is the source of the error though.

**Comment by sherpashrapnel** [comment]
Nice catch, unnecessary to run sudo like that, I removed it. Will fix the systemd-service file too. I will try to figure out if it's only Nextcloud that gets affected, so far no weird behavior with static https-websites. Thanks for coding this project btw, it's cool.

**Comment by Johann150** [comment]
Are you still experiencing this issue?
