### ISSUE TITLE
Automatic generation of certificates

### ISSUE THREAD

**Issue by ddevault** [mbrubeck/agate#41]
agate should automatically generate certificates without user intervention. Certificates are complicated and easy to get wrong, but since gemini uses a TOFU system, agate can safely generate a self-signed certificate itself, following best practices and never leaving the user burdened with completing an error prone process manually.

**Comment by Johann150** [comment]
That is why there are recommendations in the README and why there also is an install script (at least for Debian, feel free to contribute more) that sets up certificates. Using the setup script should provide a process "without user intervention" already.

**Comment by ddevault** [comment]
"Following the readme" is a long shot from zero-config TLS.

**Comment by Johann150** [comment]
Yes I did notice that many people don't seem to note lest use the files in `tools/`. On the other hand, Agate is supposed to be a "very simple Gemini server", with simple in the sense of simple implementation, which is why I am reluctant to add this.
Any way or another, I will first wait for #40 to be finished before adding this.

**Comment by Johann150** [comment]
implemented in 2213b055dcf3978da3f8f81d7ec500611be23bf8

* Ed25519 algorithm (ECDSA can optionally be selected via command line argument)
* used library defaults to `not after 4096-01-01`
* Common Name and Subject alt name are set to the hostname

**Comment by ddevault** [comment]
Thanks!
