### ISSUE TITLE
v3.0.0 Fails to build from source on Debian 10 (buster)

### ISSUE THREAD

**Issue by erwaelde** [mbrubeck/agate#43]
Hello,
I'm using Debian stable (10 buster).
I downloaded the new version 3.0.0 tarball.
`cargo build --release` fails with
```
   Compiling yasna v0.3.2
   Compiling rustls v0.19.0
   Compiling rcgen v0.8.9
error[E0658]: use of unstable library feature 'matches_macro'
   --> /home/ew/.cargo/registry/src/github.com-1ecc6299db9ec823/rcgen-0.8.9/src/lib.rs:738:5
    |
738 |                 matches!(self.is_ca, IsCa::Ca(_)) ||
    |                 ^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: could not compile `rcgen`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Maybe this is interesting, maybe not.
Maybe this is due to some Debian versioning what-do-I-know.

Cheers,
erwaelde

```
$ sha256sum ../agate-v3.0.0.tar.gz 
dac1370703cd4f9f9947a1b2b7fb3a05f081b6ac9f82a21fb7076fc6126b3f5f  ../agate-v3.0.0.tar.gz
$ rustc --version
rustc 1.41.1
$ cargo --version
cargo 1.42.1
```

**Comment by Johann150** [comment]
The mentioned macro has been stabilized in Rust version `1.42.0`, so that seems to be the minimal version to compile `rcgen`. I have not checked what minimum Rust version the other dependencies have so that might still not work.

The solution would be to update your Rust compiler and tooling to the latest version. Since Rust is not packaged on Debian AFAIK you cannot update it with apt. Instead you probably used rustup and you should be able to update with the command `rustup update`.

**Comment by erwaelde** [comment]
Hello Matt,
thanks for the info. It does build on Debian testing (11, bullseye) with rust 1.48

   Compiling rcgen v0.8.9
   Compiling tokio-macros v1.1.0
   Compiling tokio-rustls v0.22.0
   Compiling agate v3.0.0 (/home/ew/Projekte/18_gemini/agate/agate-3.0.0)
    Finished release [optimized] target(s) in 8m 24s

Cheers,
erwaelde
