### ISSUE TITLE
no server certificate chain resolved

### ISSUE THREAD

**Issue by FoxKyong** [mbrubeck/agate#54]
Hi,
I have strange problem after upgrading Agate to version 3.0.x. I was accessing my gemini pages both with IP and DNS. IP at my local network because if I test anything I like using IPs instead of DNS. I converted my current certificates to DER format as requested for version 3.0.x and now I can't access my gmi pages with IP. Only DNS work. And when accessing with IP I get:
```
"" 00 "TLS error" error:unexpected error: no server certificate chain resolved
```
in server log.
I generated my original certificates like this:
```
openssl req -x509 -newkey rsa:4096 -keyout key.rsa -out cert.pem -days 3650 -nodes -subj '/CN=mydomainname.com' -addext 'subjectAltName = IP:192.168.88.13, DNS:mydomainname.com'
```
and it was working with Agate version 2.x. After upgrading I just converted them in der with:
```
openssl x509 -in cert.pem -out cert.der -outform DER
openssl rsa -in key.rsa -out key.der -outform DER
```
and I can access the server only with DNS.

**Comment by Johann150** [comment]
Agate requires TLS SNI ([Server Name Indication](https://en.wikipedia.org/wiki/Server_Name_Indication)) since version 3.0.0, as indicated in the [changelog for 3.0.0](https://github.com/mbrubeck/agate/blob/master/CHANGELOG.md#300---2021-03-27). This is required to determine which certificate should be served to the client in a scenario where multiple domains with different certificates are served by the same server. The name your client uses in the TLS handshake is then used to find the correct certificate. If you e.g. put the certificate in `.certificates/example.com`, but the TLS handshake indicates a server name of `domain.example`, you will get this error message because agate does not have a certificate for that domain, unless you have a fallback certificate/key pair, which you could try here instead. Agate will use the key/certificate pair it finds in the top level of the certificates directory if it cannot find any other matching certificates. I.e. please try moving the `key.der` and `cert.der` files up one directory level if they are currently located in a directory titled by their domain name:

```
.certificates
|-- (move files here)
`-- example.com
   `-- (move files from here)
```

By the way, setting the `subjectAltName` in the certificate will not change anything because Agate cannot read the certificate itself, since parsing the certificate would be quite complicated.

Please leave a short note whether the solution above works for you or not.

**Comment by FoxKyong** [comment]
Sadly no. I have already tried it. And subjectAltName for working for Agate 2.  Accessing IP without it didn't work but after adding I could access it with IP address. Any other suggestion what could be wrong here?

**Comment by Johann150** [comment]
I was suspecting this would not work, but now I am quite certain that the problem is that TLS SNI will not work with IP addresses. Since the Gemini protocol requires clients to use TLS SNI&sup1;, you will not be able to access the server using an IP address. Please use a domain name.

&sup1; See [the protocol specification](https://gitlab.com/gemini-specification/protocol/-/blob/9966509395335ae226bfc46cef2704b7314ec19d/specification.gmi#L53), this has been part of the protocol specification for a while. That is the reason for the respective changelog entry being in the "Fixed" section.
