### ISSUE TITLE
Unintuitive behaviour with multiple hostnames and certificates

### ISSUE THREAD

**Issue by steko** [mbrubeck/agate#55]
Hello, while setting up a new server for my capsule I was testing the new "virtual hosts" feature. I found a strange corner case that is perhaps useful to document or to improve how Agate works.
I have two `--hostname` directives, one for `gemini.iosa.it` and another for a test hostname `gemini2.iosa.it`. gemini2 is just for testing so I took advantage of automatic generation of certificates. gemini.iosa.it is the main hostname and existing capsule. I have an existing certificate and I want to keep it (already converted to DER format). So I thought the following directory structure would work:
```
.certificates
├── gemini2.iosa.it
│   ├── cert.der
│   └── key.der
└── gemini.iosa.it
    ├── cert.der
    └── key.der
```

Instead, I get the following error:
```
The certificate file for gemini.iosa.it is malformed: unexpected error: The server certificate is not valid for the given name
```

After a few failed attempts, I found out that moving the certificate and key to the parent directory, deleting the `gemini.iosa.it` directory, works just fine. Like this:
```
.certificates
├── gemini2.iosa.it
│   ├── cert.der
│   └── key.der
├── cert.der
└── key.der
```

Perhaps I am not reading well the documentation but I was convinced that the former directory structure would be the correct one.

Strangely enough, if I start over without any certificate, Agate creates a directory structure like the one I was trying to use. I hope I was clear in the description of the issue and that this can be helpful. Thanks!

**Comment by Johann150** [comment]
The structure you show first is indeed correct. The second one is also not wrong, the behaviour is just slightly different, as you noticed: The certificates directly in `.certificates` are considered the fallback keys. Since no domain name is given for them, the initial domain name check is not performed. Because of TOFU I also continue to use my old certificate this way.

The problem is probably that you are missing the `subjectAltName` field in your X.509 certificate that the TLS library (rustls) expects. You can check with `openssl x509 -noout -text -in cert.der -inform DER` that this field should exist in the generated certificate but probably not in your old certificate, since we did not include the extra argument in the certificate generation before version 3.0.0.

In my opinion this is what I wrote in the changelog for 3.0.0, maybe it was not explicit enough:

> The ability to specify a certificate and key with `--cert` and `--key` respectively has been replaced with the `--certs` option. (#40)
> Certificates are now stored in a special directory. To migrate to this version, the **keys should be stored in the `.certificates` directory** (or any other directory you specify).
> This enables us to use multiple certificates for multiple domains.
(added emphasis)
